// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockMarketBackend.Models;

#nullable disable

namespace StockMarketBackend.Migrations
{
    [DbContext(typeof(ProjektBdContext))]
    partial class ProjektBdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockMarketBackend.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Accounts__3214EC07FC35669B");

                    b.HasIndex(new[] { "UserId" }, "UQ__Accounts__1788CC4DF7CABB39")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("StockMarketBackend.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Stock");

                    b.HasKey("Id")
                        .HasName("PK__Assets__3214EC074958D7CC");

                    b.HasIndex(new[] { "Ticker" }, "UQ__Assets__42AC12F0AFB66916")
                        .IsUnique();

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("StockMarketBackend.Models.MarketDatum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateOnly>("DataDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("High")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("Low")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("Open")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("Id")
                        .HasName("PK__MarketDa__3214EC07A8247469");

                    b.HasIndex(new[] { "AssetId", "DataDate" }, "UQ__MarketDa__266A55EF0343F2FF")
                        .IsUnique();

                    b.ToTable("MarketData");
                });

            modelBuilder.Entity("StockMarketBackend.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<decimal>("AverageCost")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 6)");

                    b.HasKey("Id")
                        .HasName("PK__Position__3214EC072568E82B");

                    b.HasIndex("AssetId");

                    b.HasIndex(new[] { "AccountId", "AssetId" }, "UQ__Position__00A93792BD49D5A0")
                        .IsUnique();

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("StockMarketBackend.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("Profit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__Transact__3214EC074F8E3788");

                    b.HasIndex("AccountId");

                    b.HasIndex("AssetId");

                    b.ToTable("Transactions", t =>
                        {
                            t.HasTrigger("trg_WalletAudit");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("StockMarketBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC0765D55A91");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D1053449AA4DA3")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StockMarketBackend.Models.WalletLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ChangeDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal?>("NewBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("OldBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WalletLogs");
                });

            modelBuilder.Entity("StockMarketBackend.ModelsDto.AdminUserReportResult", b =>
                {
                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalRealizedProfit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TransactionsCount")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("StockMarketBackend.ModelsDto.SystemStatsResult", b =>
                {
                    b.Property<decimal?>("TotalSystemCash")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TotalTradesExecuted")
                        .HasColumnType("int");

                    b.Property<int>("TotalUsers")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("StockMarketBackend.Models.Account", b =>
                {
                    b.HasOne("StockMarketBackend.Models.User", "User")
                        .WithOne("Account")
                        .HasForeignKey("StockMarketBackend.Models.Account", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Accounts__UserId__693CA210");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockMarketBackend.Models.MarketDatum", b =>
                {
                    b.HasOne("StockMarketBackend.Models.Asset", "Asset")
                        .WithMany("MarketData")
                        .HasForeignKey("AssetId")
                        .IsRequired()
                        .HasConstraintName("FK__MarketDat__Asset__619B8048");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("StockMarketBackend.Models.Position", b =>
                {
                    b.HasOne("StockMarketBackend.Models.Account", "Account")
                        .WithMany("Positions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Positions__Accou__6EF57B66");

                    b.HasOne("StockMarketBackend.Models.Asset", "Asset")
                        .WithMany("Positions")
                        .HasForeignKey("AssetId")
                        .IsRequired()
                        .HasConstraintName("FK__Positions__Asset__6FE99F9F");

                    b.Navigation("Account");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("StockMarketBackend.Models.Transaction", b =>
                {
                    b.HasOne("StockMarketBackend.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Transacti__Accou__73BA3083");

                    b.HasOne("StockMarketBackend.Models.Asset", "Asset")
                        .WithMany("Transactions")
                        .HasForeignKey("AssetId")
                        .IsRequired()
                        .HasConstraintName("FK__Transacti__Asset__74AE54BC");

                    b.Navigation("Account");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("StockMarketBackend.Models.Account", b =>
                {
                    b.Navigation("Positions");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("StockMarketBackend.Models.Asset", b =>
                {
                    b.Navigation("MarketData");

                    b.Navigation("Positions");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("StockMarketBackend.Models.User", b =>
                {
                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
